# Generated by Django 5.0.6 on 2024-05-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oquvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_familya', models.CharField(max_length=100)),
                ('sinf', models.CharField(max_length=4)),
                ('maktab', models.SmallIntegerField()),
                ('face_img', models.ImageField(upload_to='media')),
            ],
        ),
    ]
