# Generated by Django 5.0.6 on 2024-05-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oquvchi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oquvchi',
            name='face_img',
        ),
        migrations.AddField(
            model_name='oquvchi',
            name='face_url',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
