# Generated by Django 5.0.6 on 2024-06-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oquvchi', '0004_alter_oquvchi_face_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oquvchi',
            name='face_url',
        ),
        migrations.AddField(
            model_name='oquvchi',
            name='face_data',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
