# Generated by Django 5.0.6 on 2024-08-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telegroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oquvchi_id', models.IntegerField()),
                ('sinf', models.CharField(max_length=5)),
                ('group_id', models.IntegerField()),
                ('topic_id', models.IntegerField()),
            ],
        ),
    ]
