# Generated by Django 5.0.6 on 2024-05-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('parol', models.CharField(max_length=30)),
                ('ism_familya', models.CharField(max_length=100)),
            ],
        ),
    ]
