# Generated by Django 5.0.6 on 2024-05-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirishlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirish',
            name='sana',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='kirish',
            name='vaqt',
            field=models.TimeField(),
        ),
    ]
